RUN_STRINGS = (
    "Where do you think you're going?",
    "Huh? what? did they get away?",
    "ZZzzZZzz... Huh? what? oh, just them again, nevermind.",
    "Get back here!",
    "Not so fast...",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You run, you die.",
    "Jokes on you, I'm everywhere",
    "You're gonna regret that...",
    "You could also try /punchme, I hear that's fun.",
    "Go bother someone else, no-one here cares.",
    "You can run, but you can't hide.",
    "Is that all you've got?",
    "I'm behind you...",
    "You've got company!",
    "We can do this the easy way, or the hard way.",
    "You just don't get it, do you?",
    "Yeah, you better run!",
    "Please, remind me how much I care?",
    "I'd run faster if I were you.",
    "That's definitely the droid we're looking for.",
    "May the odds be ever in your favour.",
    "Famous last words.",
    "And they disappeared forever, never to be seen again.",
    "\"Oh, look at me! I'm so cool, I can run from a bot!\" - this person",
    "Yeah yeah, just tap /punchme already.",
    "Here, take this ring and head to Mordor while you're at it.",
    "Legend has it, they're still running...",
    "Unlike Harry Potter, your parents can't protect you from me.",
    "Fear leads to anger. Anger leads to hate. Hate leads to suffering. If you keep running in fear, you might "
    "be the next Vader.",
    "Multiple calculations later, I have decided my interest in your shenanigans is exactly 0.",
    "Legend has it, they're still running.",
    "Keep it up, not sure we want you here anyway.",
    "You're a wiza- Oh. Wait. You're not Harry, keep moving.",
    "NO RUNNING IN THE HALLWAYS!",
    "Hasta la vista, baby.",
    "Who let the dogs out?",
    "It's funny, because no one cares.",
    "Ah, what a waste. I liked that one.",
    "Frankly, my dear, I don't give a damn.",
    "My milkshake brings all the boys to yard... So run faster!",
    "You can't HANDLE the truth!",
    "A long time ago, in a galaxy far far away... Someone would've cared about that. Not anymore though.",
    "Hey, look at them! They're running from the inevitable banhammer... Cute.",
    "Han shot first. So will I.",
    "What are you running after, a white rabbit?",
    "As The Doctor would say... RUN!",
)

SLAP_SAITAMA_TEMPLATES = (
    "Slap saya lagi lalu saya akan membisukan anda.",
    "Berhenti slap saya 😡",
    [
        "Saya membisukan anda untuk beberapa saat.",  # normal reply
        "Berhenti slap saya karena saya tidak bisa membisukan anda 🤧",  # reply to admin
        "tmute"  # command
    ]
)


SLAP_TEMPLATES = (
    "{user1} menendang bokong {user2} dengan keras.",
    "{user2} berlari diatas kaktus karena mencoba kabur dari {user1}.",
    "{user2} memukul dirinya sendiri dengan {item}.",
    "{user1} menendang kepala {user2} hingga patah.",
    "{user2} dikeroyok warga karena terlalu menyebalkan.",
    "{user1} menghantam wajah {user2} menggunakan {item} dengan keras.",
    "{user2} galau berat karena cintanya ditolak {user1}.",
    "{user1} menabrak {user2} menggunakan tank baja.",
    "{user1} mengikat {user2} di kursi kemudian menghantamnya menggunakan {item}.",
    "{user2} terkena azab karena kebodohannya.",
    "{user2} ditarik paksa oleh satpol PP karena ketahuan mengamen di lampu merah.",
    "{user2} mengambil sebuah {item} kemudian {throws} itu ke kepalanya sendiri. Dasar bodoh!",
    "{user2} mengalami patah tulang karena dipukul oleh {user1}.",
    "{user2} terbawa ombak saat mencoba berenang dilaut.",
    "{user2} kencing celana karena takut melihat dirinya sendiri di cermin.",
    "{user2} mencoba mengajak {user1} untuk berkencan namun ditolak. Kasian sekali.",
    "{user2} membeli kopi sianida kemudian meminumnya sendiri.",
    "{user1} men-smackdown {user2} dengan jurus Goldberg .",
    "{user1} membenturkan kepala {user2} ke tembok.",
    "{user1} meraih {item} dan langsung {throws} itu ke kepala {user2}.",
    "{user2} mencoba memukul {user1} tapi malah dipukul balik.",
    "{user2} diam-diam menyukai {user1}.",
    "{user2} mengaku cinta mati ke {user1} namun malu mengungkapkannya.",
    "{user2} tewas karena meminum kopi buatan {user1}.",
    "{user2} sedang berada di gedung tinggi kemudian langsung melompat kebawah.",
    "{user2} sekarat karena terkena tembakan {user1}.",
    "{user2} memasukkan granat aktif kemulutnya.",
    "{user1} mengajak {user2} ketengah hutan rimba kemudian meninggalkannya}!",
    "{user2} mengajak {user1} untuk menikah namun {user1} lebih memilih orang lain.",
    "{user2} melompat dari pesawat yang sedang terbang tanpa menggunakan parasut.",
    "{user1} menyebarkan semua aib {user2} ke sosmed.",
    "{user2} digeplak dengan keras oleh {user1}.",
    "{user1} {throws} batu bata ke {user2}.",
    "{user2} got a premature burial.",
    "{user1} spammed {user2}'s email.",
    "{user1} hit {user2} with a small, interstellar spaceship.",
    "{user1} put {user2} in check-mate.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} died of hospital gangrene.",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user1} checkmated {user2} in two moves.",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",    
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",        
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} melihat {item} dan langsung mengambilnya kemudian {hits} {user2} dengan itu!",
    "{user1} menancapkan pisau ke perut {user2} hingga {user2} sekarat!",
    "{user1} meninju wajah {user2} hingga hidungnya patah!.",
    "Hai semua! ayo kita keroyok {user2}!",
    "{user1} {throws} {item} ke {user2}",
    "{user2} mengambil gesper kemudian memukulkan itu pada {user2}",
    "{user2} meraih sebuah {item} lalu {hits} dirinya sendiri",
    "{user2} mencoba mencuri {item} namun ketahuan, akhirnya dia di pukuli masyarakat setempat.",
    "{user1} mendorong {user2} kedalam lumpur hisap.",
    "{user1} menggelitik {user2} hingga lemas!",
    "{user1} menggunakan jurus kungfu untuk membuat {user2} pingsan.",
    "{user1} {hits} {user2} dengan sebuah {item}.",
    "{user1} {hits} {user2} tepat diwajahnya menggunakan{item}.",
    "{user1} {hits} {user2} dengan sangat keras menggunakan {item}.",
    "{user1} {throws} sebuah {item} ke {user2}.",
    "{user1} mengambil {item} dan {throws} itu pada {user2} sampai terkapar.",
    "{user1} melemparkan {item} tepat ke arah {user2}.",
    "{user1} kesal lalu menampar {user2} dengan {item}.",
    "{user1} menjatuhkan {user2} kemudian {hits} badannya dengan sebuah {item}.",
    "{user1} mengambil {item} dan {hits} {user2} menggunakan itu.",
    "{user1} mengikat {user2} ketiang listrik kemudian {throws} sebuah {item} ke wajahnya.",
    "{user1} mendorong dengan keras {user2} ke jurang penyesalan paling dalam.",
    "{user1} melempar granat kearah {user2}.",
    "{user1} menembak {user2} menggunakan rudal",
    "{user1} {throws} sebuah {item} ke kepala {user2} hingga pingsan.",
    "{user1} meretas akun sosmed {user2} kemudian mengganti passwordnya",
    "{user1} memanggil massa kemudian mengeroyok {user2}.",
    "{user1} menampar dengan keras {user2} menggunakan {item}.",
    "{user1} mengirim bom aktif kerumah {user2}.",
    "{user1} mencambuk {user2} menggunakan rotan!",  
    "{user1} menampol {user2} menggunakan {item}.",
)

PING_STRING = (
    "PONG 🏓!",
    "PONG 😎!",
)

ITEMS = (
    "palu",
    "catokan",
    "tongkat pramuka",
    "sekop",
    "roda gerobak",
    "gayung lope",
    "buku geografi",
    "laptop",
    "pipa besi",
    "rantai motor",
    "wajan gosong",
    "kunci inggris",
    "kursi plastik",
    "TV tabung",
    "printer",
    "aquarium",
    "toples kaca",
    "botol marjan",
    "stang motor supra",
    "knalpot motor",
    "sepatu laras",
    "shuriken",
    "helm gojek",
)

THROW = (
    "menamparkan",
    "melempar",
    "menghantamkan",
    "memukulkan",
)

HIT = (
    "menampol",
    "menampar",
    "menggeplak",
    "menghantam",
    "memukul",

)

ABUSE_STRINGS = (
    "Fuck off",
    "Stfu go fuck yourself",
    "Ur mum gey",
    "Ur dad lesbo",
    "Bsdk",
    "Nigga",
    "Ur granny tranny",
    "you noob",
    "Relax your Rear,ders nothing to fear,The Rape train is finally here",
    "Stfu bc",
    "Stfu and Gtfo U nub",
    "GTFO bsdk",
    "CUnt",
    " Gay is here",
    "Ur dad gey bc ",
)

EYES = [
    ['⌐■', '■'],
    [' ͠°', ' °'],
    ['⇀', '↼'],
    ['´• ', ' •`'],
    ['´', '`'],
    ['`', '´'],
    ['ó', 'ò'],
    ['ò', 'ó'],
    ['⸌', '⸍'],
    ['>', '<'],
    ['Ƹ̵̡', 'Ʒ'],
    ['ᗒ', 'ᗕ'],
    ['⟃', '⟄'],
    ['⪧', '⪦'],
    ['⪦', '⪧'],
    ['⪩', '⪨'],
    ['⪨', '⪩'],
    ['⪰', '⪯'],
    ['⫑', '⫒'],
    ['⨴', '⨵'],
    ['⩿', '⪀'],
    ['⩾', '⩽'],
    ['⩺', '⩹'],
    ['⩹', '⩺'],
    ['◥▶', '◀◤'],
    ['◍', '◎'],
    ['/͠-', '┐͡-\\'],
    ['⌣', '⌣”'],
    [' ͡⎚', ' ͡⎚'],
    ['≋'],
    ['૦ઁ'],
    ['  ͯ'],
    ['  ͌'],
    ['ළ'],
    ['◉'],
    ['☉'],
    ['・'],
    ['▰'],
    ['ᵔ'],
    [' ﾟ'],
    ['□'],
    ['☼'],
    ['*'],
    ['`'],
    ['⚆'],
    ['⊜'],
    ['>'],
    ['❍'],
    ['￣'],
    ['─'],
    ['✿'],
    ['•'],
    ['T'],
    ['^'],
    ['ⱺ'],
    ['@'],
    ['ȍ'],
    ['  '],
    ['  '],
    ['x'],
    ['-'],
    ['$'],
    ['Ȍ'],
    ['ʘ'],
    ['Ꝋ'],
    [''],
    ['⸟'],
    ['๏'],
    ['ⴲ'],
    ['◕'],
    ['◔'],
    ['✧'],
    ['■'],
    ['♥'],
    [' ͡°'],
    ['¬'],
    [' º '],
    ['⨶'],
    ['⨱'],
    ['⏓'],
    ['⏒'],
    ['⍜'],
    ['⍤'],
    ['ᚖ'],
    ['ᴗ'],
    ['ಠ'],
    ['σ'],
    ['☯']
]

MOUTHS = [
    ['v'],
    ['ᴥ'],
    ['ᗝ'],
    ['Ѡ'],
    ['ᗜ'],
    ['Ꮂ'],
    ['ᨓ'],
    ['ᨎ'],
    ['ヮ'],
    ['╭͜ʖ╮'],
    [' ͟ل͜'],
    [' ͜ʖ'],
    [' ͟ʖ'],
    [' ʖ̯'],
    ['ω'],
    [' ³'],
    [' ε '],
    ['﹏'],
    ['□'],
    ['ل͜'],
    ['‿'],
    ['╭╮'],
    ['‿‿'],
    ['▾'],
    ['‸'],
    ['Д'],
    ['∀'],
    ['!'],
    ['人'],
    ['.'],
    ['ロ'],
    ['_'],
    ['෴'],
    ['ѽ'],
    ['ഌ'],
    ['⏠'],
    ['⏏'],
    ['⍊'],
    ['⍘'],
    ['ツ'],
    ['益'],
    ['╭∩╮'],
    ['Ĺ̯'],
    ['◡'],
    [' ͜つ']
]

EARS = [
    ['q', 'p'],
    ['ʢ', 'ʡ'],
    ['⸮', '?'],
    ['ʕ', 'ʔ'],
    ['ᖗ', 'ᖘ'],
    ['ᕦ', 'ᕥ'],
    ['ᕦ(', ')ᕥ'],
    ['ᕙ(', ')ᕗ'],
    ['ᘳ', 'ᘰ'],
    ['ᕮ', 'ᕭ'],
    ['ᕳ', 'ᕲ'],
    ['(', ')'],
    ['[', ']'],
    ['¯\\_', '_/¯'],
    ['୧', '୨'],
    ['୨', '୧'],
    ['⤜(', ')⤏'],
    ['☞', '☞'],
    ['ᑫ', 'ᑷ'],
    ['ᑴ', 'ᑷ'],
    ['ヽ(', ')ﾉ'],
    ['\\(', ')/'],
    ['乁(', ')ㄏ'],
    ['└[', ']┘'],
    ['(づ', ')づ'],
    ['(ง', ')ง'],
    ['⎝', '⎠'],
    ['ლ(', 'ლ)'],
    ['ᕕ(', ')ᕗ'],
    ['(∩', ')⊃━☆ﾟ.*'],
]

TOSS = (
    "Heads",
    "Tails",
)

DECIDE = (
    "Yes.",
    "NoU.",
    "Maybe."
)

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables."
)
